### ISSUE TITLE
Failed to build bcrypt cryptography

### ISSUE THREAD

**Issue by ahmadihamid** [medanisjbara/synapse-termux#3]
I failed to build using install script.
Here is the terminal output : https://gist.github.com/ahmadihamid/40d41c9439cb60c7585f7f44894d4e7b

**Comment by medanisjbara** [comment]
Thank you for reporting this.
It seems like the error is also reproducible on my end too. So it is not something related to CPU architecture. Most likely, it is due to an update that happened and broke compatibility.
Luckily, 10 days ago, Both `python-cryptography` and `python-bcrypt` became available in the termux repositories, and relying on that is more reliable than building it via rust.
I will update both the guide and the script to use those instead.

**Comment by medanisjbara** [comment]
A small update: Fortunately the problem seems to be in the rust compiler on termux. [this issue](https://github.com/termux/termux-packages/issues/12260) seem to be related. It is also new.
Thankfully, a user have reported a working workaround that can be easily be implemented.
deprecating the need to give up virtualenv to use `python-bcrypt` installed via `pkg` (I was not able to get it to work inside virtualenv so I was probably going to give it up at that point).

**Comment by ahmadihamid** [comment]
> A small update: Fortunately the problem seems to be in the rust compiler on termux. [this issue](https://github.com/termux/termux-packages/issues/12260) seem to be related. It is also new. Thankfully, a user have reported a working workaround that can be easily be implemented. deprecating the need to give up virtualenv to use `python-bcrypt` installed via `pkg` (I was not able to get it to work inside virtualenv so I was probably going to give it up at that point).

It works! Thanks a lot..

**Comment by medanisjbara** [comment]
Thanks a lot for testing this! I was afraid to add the config without running tests on this. But I didn't find the chance to test it.
I will implement it in the script.

**Comment by medanisjbara** [comment]
Done
